// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB71ckHyRxLwlEDx239iicxFop-8_XXJRo',
    appId: '1:897634921754:web:59d91b0220bdcf9e5750a3',
    messagingSenderId: '897634921754',
    projectId: 'scamalert-5ey78',
    authDomain: 'scamalert-5ey78.firebaseapp.com',
    storageBucket: 'scamalert-5ey78.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1gcgNJsBQVc-KH72-jgINHR__YeYsY44',
    appId: '1:897634921754:android:c18423c5e16c09495750a3',
    messagingSenderId: '897634921754',
    projectId: 'scamalert-5ey78',
    storageBucket: 'scamalert-5ey78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ZkLHbdhiXOAfrm5lhVImvXSoA7bVw0s',
    appId: '1:897634921754:ios:175e4713ca3c77f35750a3',
    messagingSenderId: '897634921754',
    projectId: 'scamalert-5ey78',
    storageBucket: 'scamalert-5ey78.firebasestorage.app',
    iosBundleId: 'com.example.marketbujho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3ZkLHbdhiXOAfrm5lhVImvXSoA7bVw0s',
    appId: '1:897634921754:ios:175e4713ca3c77f35750a3',
    messagingSenderId: '897634921754',
    projectId: 'scamalert-5ey78',
    storageBucket: 'scamalert-5ey78.firebasestorage.app',
    iosBundleId: 'com.example.marketbujho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB71ckHyRxLwlEDx239iicxFop-8_XXJRo',
    appId: '1:897634921754:web:c2adf32ae7c14e6a5750a3',
    messagingSenderId: '897634921754',
    projectId: 'scamalert-5ey78',
    authDomain: 'scamalert-5ey78.firebaseapp.com',
    storageBucket: 'scamalert-5ey78.firebasestorage.app',
  );
}
